title: "Bluelib Jekyll"

bluelib: 
  rulesets:
    - base.root
    - classic.root
    - glass.root
    - colors-royalblue.root
    - fonts-fira-ghpages.root

background: >-
  url(https://gh.steffo.eu/bluelib/examples/Space_Default.jpg)